required=[
  "github.com/manifoldco/promptui",
  "github.com/spf13/cobra",
  "gopkg.in/src-d/go-git.v4",
]
[[constraint]]
  name = "github.com/manifoldco/promptui"
  version = "0.3.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.4.1"

[prune]
  go-tests = true
  unused-packages = true
